# Generated by Django 5.0.6 on 2024-06-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaction',
            name='url_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
