# Generated by Django 5.0.6 on 2024-06-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(default='default_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
