# Generated by Django 5.0.6 on 2024-06-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_is_deleted'),
        ('patient', '0002_alter_patient_table'),
        ('staff', '0002_staffaction_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True)),
                ('date_issued', models.DateField()),
                ('created_by', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified_by', models.IntegerField()),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
    ]
