# Generated by Django 5.0.6 on 2024-06-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('staff', '0002_alter_staff_city_alter_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='labreport_bill',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='medicine_bill',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.patientbills'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay')], max_length=255),
        ),
    ]
