# Generated by Django 5.0.6 on 2024-07-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cholesteroltest_result_kidneyfunctiontest_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
