# Generated by Django 5.0.6 on 2024-06-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffaction',
            name='role',
        ),
        migrations.AlterField(
            model_name='staff',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StaffActionRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.staffaction')),
                ('role_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.roles')),
            ],
            options={
                'db_table': 'staff_action_roles',
            },
        ),
    ]
