# Generated by Django 5.0.6 on 2024-07-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
    ]
