# Generated by Django 5.0.6 on 2024-06-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffaction_role_alter_staff_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffactionroles',
            old_name='action_id',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='staffactionroles',
            old_name='role_id',
            new_name='role',
        ),
    ]
