# Generated by Django 5.0.6 on 2024-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_prescription_last_modified_by_labreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
