# Generated by Django 5.0.6 on 2024-06-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_city_staff_joined_staff_salary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='labreport',
            table='lab_report',
        ),
    ]
