# Generated by Django 5.0.6 on 2024-06-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_labreport_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labreport',
            name='remarks',
        ),
    ]
