# Generated by Django 5.0.6 on 2024-06-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_is_deleted'),
        ('staff', '0009_remove_labreport_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='date_issued',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor.doctor'),
        ),
    ]
