# Generated by Django 5.0.6 on 2024-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_st_sugartest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugartest',
            name='investigation',
            field=models.CharField(default='Fasting Blood Sugar, Postprandial Blood Sugar, Random Blood Sugar, HbA1c, Oral Glucose Tolerance Test (OGTT)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sugartest',
            name='reference_value',
            field=models.CharField(default='70 - 100, 70 - 140, 70 - 140, 4.0 - 5.6, 140 - 199', max_length=255),
        ),
        migrations.AlterField(
            model_name='sugartest',
            name='unit',
            field=models.CharField(default='mg/dL, mg/dL, mg/dL, %, mg/dL', max_length=255),
        ),
    ]
