# Generated by Django 5.0.6 on 2024-06-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_sugartest_investigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CholesterolTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(default='Total Cholesterol, LDL Cholesterol (Low-Density Lipoprotein), HDL Cholesterol (High-Density Lipoprotein), Triglycerides', max_length=255)),
                ('reference_value', models.CharField(default='< 200, < 100, > 40, < 150', max_length=255)),
                ('unit', models.CharField(default='mg/dL, mg/dL, mg/dL, mg/dL', max_length=255)),
            ],
            options={
                'db_table': 'cholesterol_test',
            },
        ),
        migrations.CreateModel(
            name='CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('reference_value', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ct',
            },
        ),
        migrations.CreateModel(
            name='KFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('reference_value', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'kft',
            },
        ),
        migrations.CreateModel(
            name='KidneyFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(default='Urea, Creatinine, Uric Acid, Calcium, Total, Phosphorus, Alkaline Phosphatase (ALP), Total Protein, Albumin, Sodium, Potassium, Chloride', max_length=255)),
                ('reference_value', models.CharField(default='13 - 43, 0.7 - 1.3, 3.5 - 7.2, 8.7 - 10.4, 2.4 - 5.1, 30 - 120, 5.7 - 8.2, 3.2 - 4.8, 136 - 145, 3.5 - 5.1, 98 - 107', max_length=255)),
                ('unit', models.CharField(default='mg/dL, mg/dL, mg/dL, mg/dL, mg/dL, U/L, g/dL, g/dL, mEq/L, mEq/L, mEq/L', max_length=255)),
            ],
            options={
                'db_table': 'kidney_function_test',
            },
        ),
        migrations.CreateModel(
            name='LFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('reference_value', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lft',
            },
        ),
        migrations.CreateModel(
            name='LiverFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(default='Total Bilirubin, Direct Bilirubin, Indirect Bilirubin, Aspartate Aminotransferase (AST/SGOT), Alanine Aminotransferase (ALT/SGPT), Alkaline Phosphatase (ALP), Total Protein, Albumin, Globulin, Albumin/Globulin Ratio', max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('reference_value', models.CharField(default='0.1 - 1.2, 0.0 - 0.4, 0.1 - 0.8, 5 - 40, 7 - 56, 30 - 120, 6.0 - 8.3, 3.5 - 5.0, 2.0 - 3.5, 1.0 - 2', max_length=255)),
                ('unit', models.CharField(default='mg/dL, mg/dL, mg/dL, U/L, U/L, U/L, g/dL, g/dL, g/dL, ratio', max_length=255)),
            ],
            options={
                'db_table': 'liver_function_test',
            },
        ),
    ]
