# Generated by Django 5.0.6 on 2024-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_invoice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
    ]
