# Generated by Django 5.0.6 on 2024-06-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_invoice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='cholesterol_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.cholesteroltest'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='kidney_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.kidneyfunctiontest'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='liver_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.liverfunctiontest'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='sugar_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.sugartest'),
        ),
    ]
