# Generated by Django 5.0.6 on 2024-06-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_labreport_cholesterol_test_labreport_kidney_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='category',
            field=models.CharField(choices=[('Sugar Test', 'Sugar Test'), ('Cholesterol Test', 'Cholesterol Test'), ('Liver Test', 'Liver Test'), ('Kidney Test', 'Kidney Test')], max_length=100),
        ),
    ]
