# Generated by Django 5.0.6 on 2024-06-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_labreport_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription_id',
            new_name='id',
        ),
    ]
