# Generated by Django 5.0.6 on 2024-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_rename_prescription_id_prescription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'medicine',
            },
        ),
    ]
