# Generated by Django 5.0.6 on 2024-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_cholesteroltest_price_kidneyfunctiontest_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbills',
            name='lab_report',
        ),
        migrations.RemoveField(
            model_name='patientbills',
            name='medicine',
        ),
        migrations.AddField(
            model_name='patientbills',
            name='lab_report_bill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientbills',
            name='medicine_bill',
            field=models.IntegerField(default=0),
        ),
    ]
