# Generated by Django 5.0.6 on 2024-06-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_remove_patientbills_lab_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='quantity',
        ),
    ]
