# Generated by Django 5.0.6 on 2024-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_remove_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbills',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
