# Generated by Django 5.0.6 on 2024-06-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admins',
        ),
    ]
