# Generated by Django 5.0.6 on 2024-06-10 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('checkout_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
