# Generated by Django 5.0.6 on 2024-06-26 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('General', 'General'), ('ICU', 'ICU'), ('Rooms', 'Rooms')], max_length=50)),
                ('is_vacant', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField()),
                ('disease', models.CharField(choices=[('fever', 'Fever'), ('headache', 'Headache'), ('flu', 'Flu'), ('covid', 'COVID-19'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('asthma', 'Asthma'), ('arthritis', 'Arthritis'), ('cancer', 'Cancer'), ('depression', 'Depression'), ('allergy', 'Allergy'), ('pneumonia', 'Pneumonia'), ('bronchitis', 'Bronchitis'), ('migraine', 'Migraine'), ('insomnia', 'Insomnia'), ('other', 'Other')], default='', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=7, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, default=None, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.room')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
