# Generated by Django 5.0.6 on 2024-07-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctoravailability',
            table='doctor_availability',
        ),
    ]
