# Generated by Django 5.0.6 on 2024-07-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_alter_doctoravailability_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='timeslot',
            field=models.CharField(max_length=20),
        ),
    ]
