# Generated by Django 5.0.6 on 2024-07-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_doctoravailability_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.CharField(choices=[('09:00 - 09:30', '09:00 - 09:30'), ('10:00 - 10:30', '10:00 - 10:30'), ('11:00 - 11:30', '11:00 - 11:30'), ('12:00 - 12:30', '12:00 - 12:30'), ('13:00 - 13:30', '13:00 - 13:30'), ('14:00 - 14:30', '14:00 - 14:30'), ('15:00 - 15:30', '15:00 - 15:30'), ('16:00 - 16:30', '16:00 - 16:30'), ('17:00 - 17:30', '17:00 - 17:30')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='date',
            field=models.CharField(help_text='DD-MM-YYYY'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='timeslot',
            field=models.CharField(choices=[('09:00 - 09:30', '09:00 - 09:30'), ('10:00 - 10:30', '10:00 - 10:30'), ('11:00 - 11:30', '11:00 - 11:30'), ('12:00 - 12:30', '12:00 - 12:30'), ('13:00 - 13:30', '13:00 - 13:30'), ('14:00 - 14:30', '14:00 - 14:30'), ('15:00 - 15:30', '15:00 - 15:30'), ('16:00 - 16:30', '16:00 - 16:30'), ('17:00 - 17:30', '17:00 - 17:30')], max_length=20),
        ),
    ]
