# Generated by Django 5.0.6 on 2024-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default=1234, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
